apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sql3netoperators.charts.helm.k8s.io
spec:
  group: charts.helm.k8s.io
  names:
    kind: Sql3NetOperator
    listKind: Sql3NetOperatorList
    plural: sql3netoperators
    singular: sql3netoperator
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
