version: '3'
services:
  sql3net:
    container_name: sql3net
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
      - "9090:9090"
    volumes:
      - ./filestore:/filestore
