affinity: {}
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: nicgrobler/sql3net
imagePullSecrets: []
ingress:
  annotations: {}
  enabled: false
  hosts:
  - host: sql3net.local
    paths: []
  tls: []
nameOverride: ""
nodeSelector: {}
podSecurityContext: {}
replicaCount: 1
resources: {}
securityContext: {}
service:
  port: 9090
  type: ClusterIP
serviceAccount:
  create: true
  name: null
tolerations: []
