kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sql3net-operator
subjects:
- kind: ServiceAccount
  name: sql3net-operator
roleRef:
  kind: Role
  name: sql3net-operator
  apiGroup: rbac.authorization.k8s.io
