{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sql3net-operator.serviceAccountName" . }}
  labels:
{{ include "sql3net-operator.labels" . | nindent 4 }}
{{- end -}}
